import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

/// Thrown by Firebase-backed services when Firebase could not be initialized
/// (missing google-services.json / GoogleService-Info.plist / firebase_options.dart).
class FirebaseUnavailableException implements Exception {
  final String message;
  const FirebaseUnavailableException([this.message =
      'Firebase is not configured. Run `flutterfire configure` and add '
      'google-services.json (Android) / GoogleService-Info.plist (iOS).']);

  @override
  String toString() => message;
}

/// Service responsible for initializing Firebase services.
///
/// Initialization is fail-visible, not fail-silent: when Firebase cannot be
/// initialized (config files absent or invalid), [isConfigured] stays false
/// and Firebase-backed services throw [FirebaseUnavailableException] so the
/// UI can surface an explicit offline/error state.
class FirebaseService {
  static bool _isConfigured = false;

  /// True once [init] completed successfully against real Firebase config.
  static bool get isConfigured => _isConfigured;

  static Future<void> init() async {
    try {
      // With `flutterfire configure` this becomes:
      //   await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
      // On Android without firebase_options.dart, initializeApp() picks up the
      // FirebaseOptions generated by the google-services gradle plugin when
      // google-services.json is present (see android/app/build.gradle).
      await Firebase.initializeApp();
      _isConfigured = true;
    } catch (e) {
      _isConfigured = false;
      debugPrint(
        'BAHHAR: Firebase is NOT configured (${e.runtimeType}). '
        'Add google-services.json / GoogleService-Info.plist / firebase_options.dart '
        'to enable cloud sync. The app will run with local sample data.',
      );
    }
  }
}
